### ISSUE TITLE
cronjobs Date UTC 

### ISSUE THREAD

**Issue by soufianez75** [AxaFrance/dailyclean#38]
date UTC vs date local
show the timezone ?

**Comment by samuel-jobert** [comment]
I have problems too with local vs UTC time.

When winter time (GMT+1), I have to set wanted hour minus 2.
When summer time (GMT+2), I have to set wanted hour minus 4.

I think it is from [date.js](https://github.com/AxaFrance/dailyclean/blob/main/api/web/src/date.js) where the sign of timezoneOffsetHour have to be inversed.
•	date.setHours(hourUTC **+** timezoneOffsetHour());
•	date.setHours(hourLocal **-** timezoneOffsetHour());

Because when GTM+2 timezoneOffsetHour() returns -2 for example.
